export const productActionTypes = {
    GET_ALL_PRODUCTS_PENDING: "GET_ALL_PRODUCTS_PENDING",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILED: "GET_ALL_PRODUCTS_FAILED",

    GET_PRODUCT_BY_ID_PENDING: "GET_PRODUCT_BY_ID_PENDING",
    GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
    GET_PRODUCT_BY_ID_FAILED: "GET_PRODUCT_BY_ID_FAILED",

    // ADD TO CAR
    ADD_TO_CART_PENDING: "ADD_TO_CART_PENDING",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILED: "ADD_TO_CART_FAILED",

    //REMOVE FROM THE CART

    REMOVE_FROM_CART_PENDING: "REMOVE_FROM_CART_PENDING",
    REMOVE_FROM_CART_SUCCESS: "REMOVE_FROM_CART_SUCCESS",
    REMOVE_FROM_CART_FAILED: "REMOVE_FROM_CART_FAILED",
}

export const responseStatuses = {
    error: "error",
    warning: "warning",
    info: "info",
    success: "success"
}

export const API_BASE_URL = "https://fakestoreapi.com"